#pragma once

#include <inttypes.h>

uint16_t *GetKeyStateTable();
char KeyScanCodeToASCII(const uint8_t _code, const uint8_t _uppercase);
uint32_t GetKeyStateGeneration();
uint16_t GetKeyState(uint8_t _key);

// Key states
#define HKEYSTATE_NONE				0x00
#define HKEYSTATE_KEYDOWN			0x01
#define HKEYSTATE_KEYUP				0x02

// HID scan codes
// See https://usb.org/sites/default/files/hut1_21.pdf

#define HKEY_RESERVED				0x00
#define HKEY_ERRORROLLOVER			0x01
#define HKEY_POSTFAIL				0x02
#define HKEY_ERRORUNDEFINED			0x03
#define HKEY_A						0x04
#define HKEY_B						0x05
#define HKEY_C						0x06
#define HKEY_D						0x07
#define HKEY_E						0x08
#define HKEY_F						0x09
#define HKEY_G						0x0a
#define HKEY_H						0x0b
#define HKEY_I						0x0c
#define HKEY_J						0x0d
#define HKEY_K						0x0e
#define HKEY_L						0x0f
#define HKEY_M						0x10
#define HKEY_N						0x11
#define HKEY_O						0x12
#define HKEY_P						0x13
#define HKEY_Q						0x14
#define HKEY_R						0x15
#define HKEY_S						0x16
#define HKEY_T						0x17
#define HKEY_U						0x18
#define HKEY_V						0x19
#define HKEY_W						0x1a
#define HKEY_X						0x1b
#define HKEY_Y						0x1c
#define HKEY_Z						0x1d
#define HKEY_1						0x1e
#define HKEY_2						0x1f
#define HKEY_3						0x20
#define HKEY_4						0x21
#define HKEY_5						0x22
#define HKEY_6						0x23
#define HKEY_7						0x24
#define HKEY_8						0x25
#define HKEY_9						0x26
#define HKEY_0						0x27
#define HKEY_ENTER					0x28
#define HKEY_ESCAPE					0x29
#define HKEY_DELETE					0x2A
#define HKEY_TAB					0x2B
#define HKEY_SPACEBAR				0x2C
#define HKEY_MINUS					0x2D
#define HKEY_EQUAL					0x2E
#define HKEY_SQUAREOPEN				0x2F
#define HKEY_SQUARECLOSE			0x30
#define HKEY_BACKSLASH				0x31
#define HKEY_POUND					0x32
#define HKEY_SEMICOLUMN				0x33
#define HKEY_QUOTEOPEN				0x34
#define HKEY_GRAVE					0x35
#define HKEY_COMMA					0x36
#define HKEY_PERIOD					0x37
#define HKEY_SLASH					0x38
#define HKEY_CAPSLOCK				0x39
#define HKEY_F1						0x3A
#define HKEY_F2						0x3B
#define HKEY_F3						0x3C
#define HKEY_F4						0x3D
#define HKEY_F5						0x3E
#define HKEY_F6						0x3F
#define HKEY_F7						0x40
#define HKEY_F8						0x41
#define HKEY_F9						0x42
#define HKEY_F10					0x43
#define HKEY_F11					0x44
#define HKEY_F12					0x45
#define HKEY_PRINTSCREEN			0x46
#define HKEY_SCROLLLOCK				0x47
#define HKEY_PAUSE					0x48
#define HKEY_INSERT					0x49
#define HKEY_HOME					0x4a
#define HKEY_PAGEUP					0x4b
#define HKEY_DELETEFORWARD			0x4c
#define HKEY_END					0x4d
#define HKEY_PAGEDOWN				0x4e
#define HKEY_RIGHTARROW				0x4f
#define HKEY_LEFTARROW				0x50
#define HKEY_DOWNARROW				0x51
#define HKEY_UPARROW				0x52
#define HKEY_NUMLOCK				0x53
#define HKEY_KEYPADSLASH			0x54
#define HKEY_KEYPADASTERISK			0x55
#define HKEY_KEYPADMINUS			0x56
#define HKEY_KEYPADPLUS				0x57
#define HKEY_KEYPADENTER			0x58
#define HKEY_KEYPAD1				0x59
#define HKEY_KEYPAD2				0x5a
#define HKEY_KEYPAD3				0x5b
#define HKEY_KEYPAD4				0x5c
#define HKEY_KEYPAD5				0x5d
#define HKEY_KEYPAD6				0x5e
#define HKEY_KEYPAD7				0x5f
#define HKEY_KEYPAD8				0x60
#define HKEY_KEYPAD9				0x61
#define HKEY_KEYPAD0				0x62
#define HKEY_KEYPADPERIOD			0x63
#define HKEY_PIPE					0x64
#define HKEY_APPLICATION			0x65
#define HKEY_POWER					0x66
#define HKEY_KEYPADEQUAL			0x67
#define HKEY_F13					0x68
#define HKEY_F14					0x69
#define HKEY_F15					0x6a
#define HKEY_F16					0x6b
#define HKEY_F17					0x6c
#define HKEY_F18					0x6d
#define HKEY_F19					0x6e
#define HKEY_F20					0x6f
#define HKEY_F21					0x70
#define HKEY_F22					0x71
#define HKEY_F23					0x72
#define HKEY_F24					0x73
#define HKEY_EXECUTE				0x74
#define HKEY_HELP					0x75
#define HKEY_MENU					0x76
#define HKEY_SELECT					0x77
#define HKEY_STOP					0x78
#define HKEY_AGAIN					0x79
#define HKEY_UNDO					0x7a
#define HKEY_CUT					0x7b
#define HKEY_COPY					0x7c
#define HKEY_PASTE					0x7d
#define HKEY_FIND					0x7e
#define HKEY_MUTE					0x7f
#define HKEY_VOLUMEUP				0x80
#define HKEY_VOLUMEDOWN				0x81
#define HKEY_LOCKINGCAPSLOCK		0x82
#define HKEY_LOCKINGNUMLOCK			0x83
#define HKEY_LOCKINGSCROLLOCK		0x84
#define HKEY_KEYPADCOMMA			0x85
#define HKEY_KEYPADEQUALSIGN		0x86
#define HKEY_INTERNATIONAL1			0x87
#define HKEY_INTERNATIONAL2			0x88
#define HKEY_INTERNATIONAL3			0x89
#define HKEY_INTERNATIONAL4			0x8a
#define HKEY_INTERNATIONAL5			0x8b
#define HKEY_INTERNATIONAL6			0x8c
#define HKEY_INTERNATIONAL7			0x8d
#define HKEY_INTERNATIONAL8			0x8e
#define HKEY_INTERNATIONAL9			0x8f
#define HKEY_LANG1					0x90
#define HKEY_LANG2					0x91
#define HKEY_LANG3					0x92
#define HKEY_LANG4					0x93
#define HKEY_LANG5					0x94
#define HKEY_LANG6					0x95
#define HKEY_LANG7					0x96
#define HKEY_LANG8					0x97
#define HKEY_LANG9					0x98
#define HKEY_ALTERNATEERASE			0x99
#define HKEY_SYSREQ					0x9a
#define HKEY_CANCEL					0x9b
#define HKEY_CLEAR					0x9c
#define HKEY_PRIOR					0x9d
#define HKEY_RETURN					0x9e
#define HKEY_SEPARATOR				0x9f
#define HKEY_OUT					0xa0
#define HKEY_OPER					0xa1
#define HKEY_CLEARAGAIN				0xa2
#define HKEY_CRSEL					0xa3
#define HKEY_EXSEL					0xa4
// a5-af: reserver
#define HKEY_KEYPAD00				0xb0
#define HKEY_KEYPAD000				0xb1
#define HKEY_THOUSANDSSEPERATOR		0xb2
#define HKEY_DECIMALSEPERATOR		0xb3
#define HKEY_CURRENCYUNIT			0xb4
#define HKEY_CURRENCYSUBUNIT		0xb5
#define HKEY_KEYPADOPENPAREN		0xb6
#define HKEY_KEYPADCLOSEPAREN		0xb7
#define HKEY_KEYPADOPENELIP			0xb8
#define HKEY_KEYPADCLOSEELIP		0xb9
#define HKEY_KEYPADTAB				0xba
#define HKEY_KEYPADBACKSPACE		0xbb
#define HKEY_KEYPADA				0xbc
#define HKEY_KEYPADB				0xbd
#define HKEY_KEYPADC				0xbe
#define HKEY_KEYPADD				0xbf
#define HKEY_KEYPADE				0xc0
#define HKEY_KEYPADF				0xc1
#define HKEY_KEYPADXOR				0xc2
#define HKEY_KEYPADCIRCUMFLEX		0xc3
#define HKEY_KEYPADPERCENT			0xc4
#define HKEY_KEYPADLESS				0xc5
#define HKEY_KEYPADGREATER			0xc6
#define HKEY_KEYPADAND				0xc7
#define HKEY_KEYPADDOUBLEAND		0xc8
#define HKEY_KEYPADPIPE				0xc9
#define HKEY_KEYPADDOUBLEPIPE		0xca
#define HKEY_KEYPADCOLUMN			0xcb
#define HKEY_KEYPADPOUND			0xcc
#define HKEY_KEYPADSPACE			0xcd
#define HKEY_KEYPADAT				0xce
#define HKEY_KEYPADEXCLAMATION		0xcf
#define HKEY_KEYPADMEMSTORE			0xd0
#define HKEY_KEYPADMEMRECALL		0xd1
#define HKEY_KEYPADMEMCLEAR			0xd2
#define HKEY_KEYPADMEMADD			0xd3
#define HKEY_KEYPADMEMSUBTRACT		0xd4
#define HKEY_KEYPADMEMMULTIPLY		0xd5
#define HKEY_KEYPADMEMDIVIDE		0xd6
#define HKEY_KEYPADPLUSMINUS		0xd7
#define HKEY_KEYPADCLEAR			0xd8
#define HKEY_KEYPADCLEARENTRY		0xd9
#define HKEY_KEYPADBINARY			0xda
#define HKEY_KEYPADOCTAL			0xdb
#define HKEY_KEYPADDECIMAL			0xdc
#define HKEY_KEYPADHEXADECIMAL		0xdd
// 0xde-0xdf: reserved
#define HKEY_LEFTCONTROL			0xe0
#define HKEY_LEFTSHIFT				0xe1
#define HKEY_LEFTALT				0xe2
#define HKEY_LEFTGUI				0xe3
#define HKEY_RIGHTCONTROL			0xe4
#define HKEY_RIGHTSHIFT				0xe5
#define HKEY_RIGHTALT				0xe6
#define HKEY_RIGHTGUI				0xe7
// 0xe8-0xffff: reserved

// LED page:
#define HLED_UNDEFINED				0x00
#define HLED_NUMLOCK				0x01
#define HLED_CAPSLOCK				0x02
#define HLED_SCROLLOCK				0x03
#define HLED_COMPOSE				0x04
#define HLED_KANA					0x05
#define HLED_POWER					0x06
#define HLED_SHIFT					0x07
#define HLED_DND					0x08
#define HLED_MUTE					0x09
#define HLED_TONEENABLE				0x0a
#define HLED_HIGHCUTFILTER			0x0b
#define HLED_LOWCUTFILTER			0x0c
#define HLED_EQUALIZERENA			0x0d
#define HLED_SOUNDFIELDON			0x0e
#define HLED_SURROUNDON				0x0f
#define HLED_REPEAT					0x10
#define HLED_STEREO					0x11
#define HLED_SAMPLIGRATEDETECT		0x12
#define HLED_SPINNING				0x13
#define HLED_CAV					0x14
#define HLED_CLV					0x15
#define HLED_RECORDINGFORMATDETECT	0x16
#define HLED_OFFHOOK				0x17
#define HLED_RING					0x18
#define HLED_MESSAGEWAITING			0x19
#define HLED_DATAMODE				0x1a
#define HLED_BATTERYOPERATION		0x1b
#define HLED_BATTERYOK				0x1c
#define HLED_BATERRYLOW				0x1d
#define HLED_SPEAKER				0x1e
#define HLED_HEADSET				0x1f
#define HLED_HOLD					0x20
#define HLED_MICROPHONE				0x21
#define HLED_COVERAGE				0x22
#define HLED_NIGHTMODE				0x23
#define HLED_SENDCALLS				0x24
#define HLED_CALLPICKUP				0x25
#define HLED_CONFERENCE				0x26
#define HLED_STANDBY				0x27
#define HLED_CAMERAON				0x28
#define HLED_CAMERAOFF				0x29
#define HLED_ONLINE					0x2a
#define HLED_OFFLINE				0x2b
#define HLED_BUSY					0x2c
#define HLED_READY					0x2d
#define HLED_PAPEROUT				0x2e
#define HLED_PAPERJAM				0x2f
#define HLED_REMOTE					0x30
#define HLED_FORWARD				0x31
#define HLED_REVERSE				0x32
#define HLED_STOP					0x33
#define HLED_REWIND					0x34
#define HLED_FASTFORWARD			0x35
#define HLED_PLAY					0x36
#define HLED_PAUSE					0x37
#define HLED_RECORD					0x38
#define HLED_ERROR					0x39

#define HLED_USAGESELIND			0x3a
#define HLED_USAGEINUSEIND			0x3b
#define HLED_USAGEMULTIMODEIND		0x3c
#define HLED_INDICATORON			0x3d
#define HLED_INDICATORFLASH			0x3e
#define HLED_INDICATORSLOWBLINK		0x3f
#define HLED_INDICATORFASTBLINK		0x40
#define HLED_INDICATOROFF			0x41
#define HLED_FLASHONTIME			0x42
#define HLED_SLOWBLINKONTIME		0x43
#define HLED_SLOWBLINKOFFTIME		0x44
#define HLED_FASTBLINKONTIME		0x45
#define HLED_FASTBLINKOFFTIME		0x46
#define HLED_USAGEINDCOLOR			0x47
#define HLED_INDRED					0x48
#define HLED_INDGREEN				0x49
#define HLED_INDAMBER				0x4a
#define HLED_GENERICINDICATO		0x4b
#define HLED_SYSTEMSUSPEND			0x4c
#define HLED_EXTERNALPOWERCONN		0x4d
#define HLED_INDBLUE				0x4e
#define HLED_INDORANGE				0x4f
#define HLED_GOODSTATUS				0x50
#define HLED_WARNINGSTATUS			0x51
#define HLED_RGBLED					0x52
#define HLED_REGLEDCHANNEL			0x53
#define HLED_BLUELEDCHANNEL			0x54
#define HLED_GREENLEDCHANNEL		0x55
#define HLED_LEDINTENSITY			0x56
// 0x57-0x5f: Reserved
#define HLED_PLAYERINDICATOR		0x60
#define HLED_PLAYER1				0x61
#define HLED_PLAYER2				0x62
#define HLED_PLAYER3				0x63
#define HLED_PLAYER4				0x64
#define HLED_PLAYER5				0x65
#define HLED_PLAYER6				0x66
#define HLED_PLAYER7				0x67
#define HLED_PLAYER8				0x68
// 0x69-0xffff: Reserved