M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.10.1} date Sat 15 Jul 2023 01:04:19 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-15T13:04:19-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X4.8051Y-1.1513
X5.0807Y-1.1513
T0
M30
